
package com.amma;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class login extends javax.swing.JFrame {
    

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

      errLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(450, 475));
        setMinimumSize(new java.awt.Dimension(450, 475));
        setPreferredSize(new java.awt.Dimension(450, 475));
        getContentPane().setLayout(null);
        
        getContentPane().add(getHeadingPanel());
        getContentPane().add(getInputPanel());

        pack();
    }// </editor-fold> 
    
    private JPanel getHeadingPanel() {
        JButton loginButton = new javax.swing.JButton();
        JButton signupButton = new javax.swing.JButton();
        JPanel headerPanel = new javax.swing.JPanel();
        JLabel headerLabel = new javax.swing.JLabel();
        /*signupButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        signupButton.setText("Signup");
        signupButton.addActionListener(this::signupButtonActionPerformed);
        getContentPane().add(signupButton);
        signupButton.setBounds(40, 370, 90, 40);*/

        loginButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(this::loginButtonActionPerformed);
        getContentPane().add(loginButton);
        loginButton.setBounds(150, 370, 90, 40);

        headerPanel.setBackground(new java.awt.Color(0, 255, 255));

        headerLabel.setBackground(new java.awt.Color(0 ,0 ,0));
        headerLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(0, 0, 0));
        headerLabel.setText("AMMA: Ask M(m)e Anything");

        headerPanel.setLayout(null);
        headerPanel.setBounds(0, 0, 430, 100);
        return headerPanel;
    }
    
    private JPanel getInputPanel() {
        JPanel inputPanel = new JPanel();
        JLabel loginLabel = new JLabel();
        JLabel usernameLabel = new JLabel();
        JLabel passwordLabel = new JLabel();
        errLabel = new JLabel();
        passwordField = new JPasswordField();
        textField = new JTextField();
        inputPanel.setBackground(new java.awt.Color(0, 0, 0));
        inputPanel.setLayout(null);
        
        errLabel.setFont(new java.awt.Font("Tahoma", 0, 20));
        errLabel.setForeground(new java.awt.Color(255, 0, 0));
        errLabel.setText("");
        errLabel.setBounds(80, 170, 300, 100);
        inputPanel.add(errLabel);
      

        loginLabel.setBackground(new java.awt.Color(0, 255, 255));
        loginLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(0, 255, 255));
        loginLabel.setText("Login");
        inputPanel.add(loginLabel);
        loginLabel.setBounds(150, 10, 104, 44);

        usernameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(0, 255, 255));
        usernameLabel.setText("User Name:");
        inputPanel.add(usernameLabel);
        usernameLabel.setBounds(50, 90, 120, 22);
        inputPanel.add(passwordField);
        passwordField.setBounds(190, 150, 145, 22);
        inputPanel.add(textField);
        textField.setBounds(190, 90, 145, 22);

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 255, 255));
        passwordLabel.setText("Password:");
        inputPanel.add(passwordLabel);
        passwordLabel.setBounds(60, 150, 100, 22);

        inputPanel.setBounds(0, 100, 430, 340);
        return inputPanel;
    }
    
    private String validate(String uname, String pwd) {
        if (!(uname != null && uname.length() != 0))
            return "Username is required.";
        else if (!(pwd != null && pwd.length() != 0))
            return "Password is required";
        
        return "";       
     }
    
    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Signup su = new Signup();
        //su.setVisible(true);
        //TODO: 
        
    }
       

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // validate the input
        String uname = textField.getText();
        String pwd = new String(passwordField.getPassword());
        String res = validate(uname, pwd);
        if (res.length() > 0) {
            System.out.println(res);
            errLabel.setText(res);
            return;
        }
        
        int uid = new AmmaDAO().Login(uname, pwd);
        if (uid <= 0)
            errLabel.setText("Invalid User Name or Password");
            
            gotoDashboard(uid);
    }
    
    private void gotoDashboard(int uid) {
        
        Dashboard dash = new Dashboard(uid);
        dash.setVisible(true);
   
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    
    
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField textField;
    private javax.swing.JLabel errLabel;
    // End of variables declaration                   
}